services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Sypets\Autofix\:
    resource: '../Classes/*'

  Sypets\Autofix\Command\FixDuplicateSlugsCommand:
    tags:
      - name: 'console.command'
        command: 'autofix:fixDuplicateSlugs'
        schedulable: true

  Sypets\Autofix\Command\GenerateSlugsCommand:
    tags:
      - name: 'console.command'
        command: 'autofix:generateSlugs'
        schedulable: true

  Sypets\Autofix\Service\SlugService:
    public: true
